### PR TITLE
Reformat using black CLI tool

### PR DESCRIPTION
**Pull request by jdcasey**

### CODE REVIEW

**Comment by jdcasey** [comment]
This one probably isn't that important, but I thought I'd see how much `black` changed the formatting. This is usually a pretty reliable way to format sources to avoid linting problems and make it more standardized.

Interestingly, it seems to have some places where `black` and `Flake8` don't agree...particularly on array ranges.

**Review by ligangty — APPROVED** [review]
LGTM. But I remember that I've also met a conflict between black and flake8 before. I don't remember which rule exactly it is, but when I use black to do format, then the flake8 complains it.

**Comment by pbabinca** [comment]
> LGTM. But I remember that I've also met a conflict between black and flake8 before. I don't remember which rule exactly it is, but when I use black to do format, then the flake8 complains it.

That's trivial to fix, see e.g. https://github.com/psf/black/blob/main/.flake8 in Black's repo.

**Comment by ligangty** [comment]
@jdcasey @pbabinca I'll close this as it has some conflicts with current stable code. I'll use black to reformat the whole code again to see if works.

**Pull request closed without merging**
