### PR TITLE
Always ignore uploading maven-metadata.xml* files

### PR DESCRIPTION
**Pull request by jdcasey**
We will always regenerate these, so always ignore them for upload.

### CODE REVIEW

**Comment by ligangty** [comment]
Um...I'm thinking why not use ignore_patterns "maven-metadata.xml.*" to filter out these files?

**Comment by jdcasey** [comment]
Does it filter on path or filename? I've been using path patterns, but couldn't get it to recognize an ignore pattern for these files.

But I guess more generally, why force configuration for something you know will always be true?

**Comment by jdcasey** [comment]
Actually, we do need this to filter on the total path (leaving off the root path or the target prefix path). Some files are hidden away in `.nexus` directories in the content we've extracted from that system, and we need a way to ignore them.

**Comment by ligangty** [comment]
It is working on files but not paths, because I'm not sure if paths will contain repeated patterns which will cause wrong filter. For example, I'm not sure if this type of path will happen if we have ignore_pattern "ignored".
foo/bar/ignored/xxxx
but actually we just want to filter this type of path:
ignored/foo/bar/xxx

**Pull request merged**
