### PR TITLE
switch to tox

### PR DESCRIPTION
**Pull request by hjmodi**
* MMENG-3141

Signed-off-by: Harsh Modi <hmodi@redhat.com>

### CODE REVIEW

**Comment by pbabinca** [comment]
@hjmodi  Is this ready for test or you are aware of any issues?

I have tried this on my RHEL 8 workstation and `mypy` env failed:

```
yumba:charon (main*) $ git pull
yumba:charon (main*) $ git pr 165         
yumba:charon (pr/165*) $ python3.9 -m venv venv@py3.9
yumba:charon (pr/165*) $ source venv@py3.9/bin/activate
(venv@py3.9) yumba:charon (pr/165*) $ pip install -e .              
(venv@py3.9) yumba:charon (pr/165*) $ tox                           
Installing missing stub packages:
/home/pbabinca/workspace/charon/.tox/mypy/bin/python -m pip install types-PyYAML types-requests types-setuptools

Collecting types-PyYAML
  Using cached types_PyYAML-6.0.12-py3-none-any.whl (14 kB)
Collecting types-requests
  Using cached types_requests-2.28.11.2-py3-none-any.whl (14 kB)
Collecting types-setuptools
  Using cached types_setuptools-65.4.0.0-py3-none-any.whl (49 kB)
Collecting types-urllib3<1.27
  Using cached types_urllib3-1.26.25-py3-none-any.whl (14 kB)
Installing collected packages: types-urllib3, types-setuptools, types-PyYAML, types-requests
Successfully installed types-PyYAML-6.0.12 types-requests-2.28.11.2 types-setuptools-65.4.0.0 types-urllib3-1.26.25

charon/utils/logs.py:79: error: Module "logging" is not valid as a type
charon/utils/logs.py:89: error: logging? has no attribute "addHandler"
charon/storage.py:93: error: Incompatible return value type (got "Optional[str]", expected "str")
charon/storage.py:243: error: Missing return statement
charon/storage.py:280: error: Argument 1 to "__path_handler_count_wrapper" of "S3Client" has incompatible type "Callable[[str, str, int, int, List[str]], Coroutine[Any, Any, Any]]"; expected "Callable[[str, str, int, int, List[str], Semaphore], Awaitable[bool]]"
charon/storage.py:413: error: Argument 1 to "__path_handler_count_wrapper" of "S3Client" has incompatible type "Callable[[str, str, int, int, List[str]], Coroutine[Any, Any, Any]]"; expected "Callable[[str, str, int, int, List[str], Semaphore], Awaitable[bool]]"
charon/storage.py:540: error: Argument 1 to "__path_handler_count_wrapper" of "S3Client" has incompatible type "Callable[[str, str, int, int, List[str]], Coroutine[Any, Any, Any]]"; expected "Callable[[str, str, int, int, List[str], Semaphore], Awaitable[bool]]"
charon/storage.py:735: error: Too few arguments
charon/storage.py:739: error: Incompatible return value type (got "Callable[[str, str, int, int, List[str]], Coroutine[Any, Any, Any]]", expected "Callable[[str, str, int, int, List[str], Semaphore], Awaitable[bool]]")
charon/storage.py:749: error: Need type annotation for "failed_paths" (hint: "failed_paths: List[<type>] = ...")
charon/storage.py:759: error: Too few arguments
charon/config.py:57: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, PathLike[str]]"
charon/utils/archive.py:107: error: Missing return statement
charon/pkgs/indexing.py:30: error: Missing return statement
charon/pkgs/indexing.py:85: error: Incompatible types in assignment (expression has type "List[str]", variable has type "Set[str]")
charon/pkgs/indexing.py:130: error: Argument "target" to "delete_files" of "S3Client" has incompatible type "Tuple[str, Optional[str]]"; expected "Tuple[str, str]"
charon/pkgs/indexing.py:148: error: Incompatible return value type (got "Optional[str]", expected "str")
charon/pkgs/indexing.py:162: error: Argument "items" to "IndexedHTML" has incompatible type "List[str]"; expected "Set[str]"
charon/pkgs/npm.py:91: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/npm.py:101: error: Argument 1 to "__get_path_tree" has incompatible type "List[Any]"; expected "str"
charon/pkgs/npm.py:168: error: Argument 3 to "generate_indexes" has incompatible type "Set[str]"; expected "List[str]"
charon/pkgs/npm.py:216: error: Argument 1 to "__get_path_tree" has incompatible type "List[Any]"; expected "str"
charon/pkgs/npm.py:220: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/npm.py:279: error: Argument 3 to "generate_indexes" has incompatible type "Set[str]"; expected "List[str]"
charon/pkgs/npm.py:298: error: Incompatible return value type (got "Tuple[str, bool]", expected "Tuple[str, str]")
charon/pkgs/npm.py:301: error: Missing return statement
charon/pkgs/npm.py:381: error: Return value expected
charon/pkgs/npm.py:439: error: Invalid type comment or annotation
charon/pkgs/npm.py:439: note: Suggestion: use list[...] instead of list(...)
charon/pkgs/npm.py:512: error: Missing return statement
charon/pkgs/maven.py:199: error: Need type annotation for "gavs" (hint: "gavs: Dict[<type>, <type>] = ...")
charon/pkgs/maven.py:307: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/maven.py:310: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/maven.py:320: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/maven.py:456: error: Item "None" of "Optional[List[Tuple[str, str, str, str]]]" has no attribute "__iter__" (not iterable)
charon/pkgs/maven.py:807: error: Incompatible return value type (got "int", expected "bool")
charon/pkgs/maven.py:931: error: Need type annotation for "meta_files" (hint: "meta_files: Dict[<type>, <type>] = ...")
charon/pkgs/maven.py:1006: error: Incompatible return value type (got "Tuple[Type[List[Any]], bool]", expected "Tuple[List[str], bool]")
charon/cmd/command.py:191: error: Argument 1 to "__safe_delete" has incompatible type "Optional[str]"; expected "str"
charon/cmd/command.py:330: error: Incompatible types in assignment (expression has type "bool", variable has type "str")
charon/cmd/command.py:348: error: Argument 1 to "__safe_delete" has incompatible type "Optional[str]"; expected "str"
charon/cmd/command.py:359: error: Incompatible return value type (got "List[Tuple[str, Optional[Any], Any, Any]]", expected "List[Tuple[str, str, str, str]]")
charon/cmd/command.py:382: error: Incompatible return value type (got "None", expected "List[str]")
Found 42 errors in 8 files (checked 18 source files)
ERROR: InvocationError for command '/home/pbabinca/workspace/charon/.tox/mypy/bin/mypy --install-types --non-interactive --ignore-missing-imports --package charon' (exited with code 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
  test: commands succeeded
  flake8: commands succeeded
  pylint: commands succeeded
  bandit: commands succeeded
ERROR:   mypy: commands failed
```

**Comment by pbabinca** [comment]
I believe we dropped support for type checking because of missing rpm packages that would allow us to do so as part of %test section of rpm build.

- You could disable %test section in rpm but still allow tests with type checking by installing them in tox from PyPI.
- Or you could run only some tests in %test section and still make it possible to run remaining tests on demand by people (or CI).
- Or, if you think type checking is unnecessary burden here drop whole `mypi` env from tox.
- Other approach :)

It would be up to the maintainer (you? @sswguo ? @ligangty ?) to decide which path to go.

**Review by ligangty — COMMENTED** [review]
Generally LGTM.
@pbabinca @hjmodi  For mypy type checking, I'm not sure of the following 2 points:
* How many code changes will it bring in?
* RPM package dependency  missing as you mentioned?
If there are too many code changes will bring in or rpm package not included in our internal repo, maybe we should disable it now, but we can improve the types in future code fixing continually. WDTY?

**Comment by hjmodi** [comment]
> Generally LGTM. @pbabinca @hjmodi For mypy type checking, I'm not sure of the following 2 points:
> 
> * How many code changes will it bring in?
> * RPM package dependency  missing as you mentioned?
>   If there are too many code changes will bring in or rpm package not included in our internal repo, maybe we should disable it now, but we can improve the types in future code fixing continually. WDTY?

hmm, yes it'll be multiple code changes to get it to pass and also it might be difficult to get the RPM deps(will need to look into this). So we can disable it for now.

**Review by ligangty — APPROVED** [review]
LGTM

**Pull request merged**
